import Head from 'next/head'
import s from '../styles/Home.module.scss'
import React from "react";
import { BsFillArrowUpSquareFill} from "react-icons/bs";

import Content from '../cop/content/content.js';
import { motion, AnimatePresence } from "framer-motion"
import Haader from '../cop/Header/Header';
import Footer from '../cop/footer/footer';
export default function Home() {
  let bleck = () => {
 
  }
  return (

    <AnimatePresence exitBeforeEnter>
      <div onClick={bleck} className={s.div}>

        <Head>
          <title>animation</title>
          <meta name="animation" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Haader />
        </div><a href='#' className={s.s} >
< BsFillArrowUpSquareFill/>
          
        </a>
        <div>
          <Content />
        </div>

        <footer className={s.footer}>
<Footer/>
        </footer>
      </div>
    </AnimatePresence>
  )
}
